version: '3.8'

name: transcendence-dev-db
services:
  ## Database ##
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db
    ports:
      - 5432:5432

volumes:
  db_data:

networks:
  db:
    driver: bridge
