export enum GameEvent {
  Paddle = 'Paddle',
  Bounce = 'Bounce',
  Countdown = 'Countdown',
  BonusQueue = 'BonusQueue',
  ClassicQueue = 'ClassicQueue',
  LeaveQueue = 'LeaveQueue',
  Victory = 'Victory',
  Defeat = 'Defeat',
  Fireball = 'Fireball',
  ClassicBall = 'ClassicBall',
  YourPoint = 'YourPoint',
  OpponentPoint = 'OpponentPoint',
  LeftPick = 'LeftPick',
  RightPick = 'RightPick',
  Remaining = 'Remaining',
  Start = 'Start',
  BallSpeed = 'BallSpeed',
}
