export enum ChatEvent {
  Message = 'message',
  Join = 'join',
  Leave = 'leave',
  Block = 'block',
  Unblock = 'unblock',
  Invite = 'invite',
  Create = 'create',
  MessageHistory = 'history',
  UpdateChannel = 'updateChannel',
  ChannelList = 'channelList',
  JoinedChannels = 'joinedChannels',
  UserList = 'userList',
  BlockedUsersList = 'blockList',
  Promote = 'promote',
  Demote = 'demote',
  Mute = 'mute',
}
