FROM node:18

RUN npm i -g pnpm
ENV PNPM_HOME=/pnpm

WORKDIR /app
COPY ./package.json ./pnpm-lock.yaml ./
RUN pnpm install

COPY ./ ./

CMD [ "/bin/bash", "-c", "pnpm i --silent && pnpm prisma migrate deploy && pnpm prisma generate && pnpm run dev" ]