FROM node:18

RUN npm i -g pnpm
ENV PNPM_HOME=/pnpm

WORKDIR /app
COPY ./package.json ./pnpm-lock.yaml ./
RUN pnpm install

COPY ./ ./

CMD [ "/bin/bash", "-c", "pnpm i --silent && pnpm dlx prisma migrate deploy && pnpm dlx prisma generate && pnpm run dev" ]