name: Lint and format backend

on:
  pull_request:
    paths-ignore:
      - front/**

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          cache-dependency-path: api/pnpm-lock.yaml

      - name: Install prettier
        run: pnpm i prettier

      - name: Format code
        run: pnpm format

      - name: Run eslint
        run: pnpm lint:fix:report
        continue-on-error: true

      - name: Annotate linting results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          report-json: eslint_report.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '**.ts'
